---
title: "Cluster analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = "/home/gnapier/Documents/SNP_analysis/")

```

<!-- Packages -->
```{r, echo=FALSE, message=F, warning=F, results="asis"}
# Read in packages:
Packages <- "https://raw.githubusercontent.com/GaryNapier/Packages_functions/master/Packages.R"
source(Packages)

```

<!-- Functions -->
```{r, echo=FALSE, message=F, warning=F, results="asis"}
# ----------
# Functions
# ----------

heaD <- function(x,...){
  head(x, ...)
}

h_col <- function(x, nrow = 6){
  head(x[, 1:10], nrow) 
}

# # Set and reset plots
reset_plot <- function(){
  par(mfrow = c(1, 1))
}

Plot_dims <- function(Rows, Cols){
  par(mfrow=c(Rows, Cols))
}

N_clusters <- function(Tree_in, Height, Min_clust_sz){
  length(unique(cutreeDynamic(as.hclust(Tree_in), 
                              cutHeight = Height,
                              minClusterSize=Min_clust_sz
  )))
}

Numeric <- function(x){
  x[, sapply(x, is.numeric)]
}

# Function to take out outliers from each group (lineage in this case) -
# adapt for your group of interest
No_outliers <- function(Data, SDs){
  # SDs <- 3.5 # How many standard devs from mean to take out
  Out <- function(Data, SDs){
    Vals <-c(mean(Data)+(sd(Data)*SDs),mean(Data)-(sd(Data)*SDs))
    # abs(Data - abs(mean(Data) - Val)) > Val
    Data > max(Vals) | Data < min(Vals)
  }
  
  # Need to order or indexing won't work
  Data <- Data[order(Data$main_lineage, Data$sub_lineage), ] 
  Outliers <- unique(c(
    as.vector(which(unlist(sapply(split(Data$V1, as.character(Data$sub_lineage)),
                                  function(x){Out(x, SDs)})))), 
    as.vector(which(unlist(sapply(split(Data$V2, as.character(Data$sub_lineage)),
                                  function(x){Out(x, SDs)}))))
  )) # unique(c(
  
  Data <- Data[-(Outliers), ]
}

# Function to subset rows of data by group (sub_lineage in this case),
# first proportional to amount of data in the group vs other groups, then
# retaining x% of rows (Retain arg - set to 0-1). Group arg - srtring of group col names
Sub_group <- function(x, Group, Retain){
  N_each_group <- plyr::count(x, eval(substitute(Group))) # Nb need library(dplyr)
  N_each_group$retain <- round(N_each_group$freq - 
                                 (N_each_group$freq*
                                    (N_each_group$freq/sum(N_each_group$freq)) ))
  
  N_each_group$retain <- round(N_each_group$retain*Retain)
  
  x_split <- split(x, as.character(x[,Group]))
  do.call("rbind", lapply(seq(x_split), function(i){
    x_split[[i]][sample(1:nrow(x_split[[i]]), 
                        N_each_group[N_each_group[, Group] == N_each_group[i,Group],
                                     "retain"]) , ]
  }))
}

Read_files <- function(File_names, Header = F, Sep = " ", Dec = "."){
  data.frame(do.call("rbind", lapply(File_names, 
                                     fread, header = Header, 
                                     sep = Sep, dec = Dec
                                     )))
}

# Function to get hierachy of lineage names. 
# e.g. get all lineages belonging to "1" will pull "1.1", "1.1.2", "1.2" etc. 
# i.e. pull all lineage names that contain the first element of 'subj'. 
# Returns INDICES of heirarchy in a list of lineages, so use like this:
# Lineage_vector[Tree("1.1", Lineage_vector)]
Tree <- function(Subj, Lins){
  N_subj <- nchar(Subj)
  Subj_split <- strsplit(Lins, split = "")
  Lins_test <- unlist(lapply(Subj_split, function(x){ paste(x[1:N_subj], collapse = "") }) )
  if (N_subj == 1){
    return(which(Lins == Subj))
    }else{
      return(grep(Subj, Lins_test))
    }
}
```

<!-- Setup -->
```{r, echo=FALSE, message=F, warning=F, results="asis"}

# ------
# Setup
# ------

setwd("/home/gnapier/Documents/SNP_analysis/")

Lin_nums <- 1:4

# Plot params
Line_width <- 0.2
Collapse <- 0.0007
Tick_sz <- 0.7
Round <- 5
Alpha <- 0.4
Ncol <- 2
Width <- 100
Height <- Width*0.4
Scale <- 3
Units <- "mm"
Labs <- labs(x = "PC1", y = "PC2")
par(mar = c(0.5, 1.5, 0.5, 1.5))
# Get lineage names of interest
Lin_names <- c("1", "2", "3", "4")
Lin_names_first_dec <- c("1.1", "1.2", "2.1", "2.2", "3.0", "3.1", "4.0", "4.1", "4.2",                          "4.3", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9")
Lin_names_all <- c(Lin_names, Lin_names_first_dec)
# Lin_names <- subset(Lin_names, subset = !(Lin_names %in% c("5", "6", "7", "BOV")))

```

<!-- Read in files/data & do merges/clean-->
```{r, echo=FALSE, message=F, warning=F, results="asis"}
# Read in sample names and (sub)lineage to merge with PCA data
Lins <- Read_files("all_lins/txt/lineages_clean.txt", Header = T, Sep = "\t")

# Read in PCA data
PCA_files_sublin <- sprintf("lin_%s/results/lin_%s_results.filt.pca.mds",
                     Lin_names_first_dec, Lin_names_first_dec)
PCAs <- Read_files(PCA_files_sublin, Header = T)

# PCA Eig files
Eig_files <- sprintf("lin_%s/results/lin_%s_results.filt.pca.eigenval",
                     Lin_names_first_dec, Lin_names_first_dec)
Eigs <- Read_files(Eig_files)
n <- length(Eig_files)
Eigs <- cbind(c(sort(rep(Lin_names, n)), sort(rep(Lin_names_first_dec, n))), 
              Eigs)
colnames(Eigs) <- c("Lin", "Eigs")

# Merge in sub lin labels
PCAs <- merge(Lins, PCAs[c(1, 4, 5)], 
                   by.x = "sample", by.y = names(PCAs)[1], sort = F)

# Add highest level lineage label
PCAs$lineage <- substr(PCAs$sub_lineage, 1, 1)
# Add group label (lin one dec place) to pca dataframe
# Need to make SUB-lin 3 and SUB-lin 4 into "3.0" and "4.0"
PCAs$sub_lineage_2 <- ifelse(nchar(substr(PCAs$sub_lineage, 1, 3)) == 1, 
                                         paste0(substr(PCAs$sub_lineage, 1, 3), ".0"), 
                                                substr(PCAs$sub_lineage, 1, 3))

# Remove sub-lineage "2" sample - only one sample so will error on cluster analysis
PCAs <- PCAs[!(PCAs["sub_lineage_2"] == "2.0"), ]
row.names(PCAs) <- PCAs[, 1]

# Read in Fastbap results (number of clusters per sublin (first decimal))
load("all_lins/R_data/Fastbap_phylo_n_clusts.rda")

# Data frame of cluster assigned to each sample (i.e.) fastbap results
Fastbap_clusters <- read.csv("all_lins/itol/fastbap_clusts.csv", header = T)


```

<!-- Clusters sublins -->
```{r, echo=FALSE, warning=F, cache = F, message=F}

message("PCA plots of each sub-lineage (first decimal place)")

# Plot each sublin (first decimal place):
theme_set(theme_classic())
PCA_plots <- list()
for(i in seq(Lin_names_first_dec)){
Data <- PCAs[PCAs["sub_lineage_2"] == Lin_names_first_dec[i], ]
PCA_plots[[i]] <- ggplot(data = Data, 
       aes(x = C1, y = C2, colour = sub_lineage))+
  geom_point(size = 1, alpha = 0.5)+
  # xlab("PC1")+ylab("PC2")+
  guides(colour = guide_legend(override.aes = list(size=3, alpha = 1),
                               ncol = 4))+
  scale_colour_manual(values = rainbow(length(unique(Data$sub_lineage))))+
  # theme(axis.text.y=element_text(size = Tick_sz, angle=45), 
  #       axis.text.x=element_text(size = Tick_sz))+
    theme(axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        ,legend.position = "bottom"
        ,legend.title = element_blank()
        , axis.title.x=element_blank()
        , axis.title.y=element_blank()
        , aspect.ratio = 1
        # ,strip.text.x = element_text(),
        # strip.text.y = element_text(),
        # strip.background = element_rect(colour="white")
        )
}

# Convert Fastbap n clusters col to numeric
# FB_df <- FB_df[!(FB_df[, "N_clusters"] == "-"), ]
# FB_df$N_clusters <- as.numeric(as.character(FB_df$N_clusters))

# Do visualisation of n clusters from fastbaps
Viz_clusts_sublin <- list()
Alpha <- 0.7
Max_clusts <- max(as.numeric(as.character(FB_df$N_clusters)), na.rm = T)
Clust_cols <- rainbow(Max_clusts, alpha = Alpha)
for (i in 1:length(unique(PCAs$sub_lineage_2))){
  
  # Get data
  Data <- Data <- PCAs[PCAs["sub_lineage_2"] == Lin_names_first_dec[i], ]
  Data <- merge(Data, Fastbap_clusters, by.x = "sample", by.y = "id")
  PCs <- Data[, c("C1", "C2")] # Subset PCs only to pass to k-means
  
  # Unique clusters from fastbaps (current first dec place sublin)
  N_clusts <- as.numeric(as.character(FB_df$N_clusters[i])) 
  # Do k-means on the PCs (to pass to fviz_cluster() - only takes k-means object)
  Km <- tryCatch({kmeans(PCs, N_clusts, nstart = 10)}, 
                 error = function(e){NA})
  # Replace with actual fastbaps clusters
  Km$cluster <- Data$clusters
  
  # Visualise clusters
  Viz_clusts_sublin[[i]] <- tryCatch({fviz_cluster(Km, PCs, labelsize = 0,
             pointsize = 1, main = NULL, ggtheme = theme_classic())+
    coord_fixed(0.8/1)+
    ylab("")+xlab("")+
    theme(axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none"
          , plot.title = element_blank()
          , aspect.ratio = 1
    )+
    scale_colour_manual(values = Clust_cols[1:N_clusts])+
    ggtitle(unique(PCAs[,"sub_lineage_2"])[i])}, 
    error = function(e){ggplot()})
}

message("Clustering of sub-lineages (first decimal place)")

for(i in 1:length(PCA_plots)){
  PCA_plots_grob <- ggplotGrob(PCA_plots[[i]])
  Viz_clusts_sublin_grob <- ggplotGrob(Viz_clusts_sublin[[i]])
  Viz_clusts_sublin_grob$heights <- PCA_plots_grob$heights
  grid.arrange(PCA_plots_grob, Viz_clusts_sublin_grob, ncol = 2)
}

```














